.TH BMPC "1" "April 2015" "1.5.0" "User Commands"

.SH NAME
bMPC \- The Bash MPD (Music Player Daemon) Client

.SH SYNOPSIS
.B bmpc \fR[OPTIONAL FLAGS]

.SH DESCRIPTION
This is a handy tool created using BASH to replicate most
of mpc's functionality. It uses built-in functionality (BASH
sockets) to communicate with MPD over a TCP port.

.SH COMMANDS
.TP
.BI add <URI>
Adds song at URI to current playlist. URI must be a full path
relative to the MPD server's top level directory. If the URI
contains spaces, it must be surrounded by single quotes (').
.TP
.BI current
Displays info on current song in a colorful format. See
the help for the optional long flag --format in the FLAGS 
section for how to format the output of this command.
.TP
.BI help
Display the help message.
.TP
.BI ls <URI>
Lists all files under the relative directory in MPD's music
directory. All URIs with spaces must be surrounded in single quotes
('). Output is given in full path relative to top level directory of 
MPD server music folder.
.TP
.BI next
Jump to next song on playlist.
.TP
.BI pause
Pauses playback at current point.
.TP
.BI play
Resumes playback from paused or stopped.
.TP
.BI playlist
Shows current playlist in order in a simple format.
.TP
.BI prev
Jump to previous song in playlist.
.TP
.BI raw
You may use this to specify a raw query to the MPD server over TCP. If
the query contains spaces, you must surround the query in single quotes (')
for it to be sent.
.TP
.BI rm <ID>
Removes song in playlist. This may take one of two arguments: the id 
(position) of the song in the playlist that you want to remove or the
pseudo argument 'current' that removes the currently playing track from
the playlist and cycles to the next song id.
.TP
.BI search <TAG> <QUERY>
Search the MPD server's database for a file with TAG that matches or contains
QUERY. You may search any TAG type that the MPD server supports. If TAG or QUERY
contains spaces, they must be surrounded in single quotes ('). Output is given
in full path relative to top level directory of MPD server music folder.
.TP
.BI set
Used to display and/or set some of the current MPD server settings. Currently,
the only supported settings are the toggline of random/repeat/crossfade.
.TP
.BI stats
Shows some useful stats about the MPD server. This includes current
MPD uptime, playtime, songs/artists/albums in database, and the date
of the last database update.
.TP
.BI status
Shows current status of MPD server. This includes current volume,
current track title, next track title, and random/repeat status.
.TP
.BI stop
Stops current playback. This will reset current song.
.TP
.BI toggle
Toggle playback between pause/play depending on current status. Useful for 
keybindings.
.TP
.BI update
Updates/refreshes the MPD server's database.
.TP
.BI vol <+/-#>
Changes the volume for the MPD server's output.
.TP
.BI wait
This puts bmpc into a listening loop that waits for the MPD server to change
playback status (next, prev, play, stop, pause). It will output every time there
is a change in status. Useful for notification scripts.

.SH FLAGS
.TP
.BI --host
Specify host of MPD server to be queried.
.TP
.BI --port
Specify port of MPD server to be queried.
.TP
.BI --pass
Specify password of MPD server to be queried.
.TP
.BI --nocolor
Strips all color from output.
.TP
.BI --format
This flag is used in conjunction with the current command to format the output. Within
single quotes ('), you may specify however you want the format to be displayed.
.br
Format Variables:
.IP
%artist%        Current track artist.
.br
%track%         Current track title.
.br
%album%         Current track album.
.br
%songid%        Position of current track in playlist.
.br
%genre%         Current track genre.
.br
%date%          Current track date.
.br
%length%        Length of current track.
.br
%currenttime%   Time elapsed in current track.
.br
%bitrate%       Bitrate of current song.
.TP
.BI --version
Display version/source information.
.TP
.BI --help|-h
Display the help message.

.SH "ENVIRONMENT VARIABLES"
All environment variables are overridden by any values specified via command line switches.
.IP MPD_HOST
Specifies the hostname of the MPD server.  This can be a hostname or an IP address.
.IP MPD_PORT
Specifies the port the MPD server is listening on.

.SH "SEE ALSO"
http://github.com/KittyKatt/bmpc

.SH AUTHOR
Created by and licensed to Brett Bohnenkamper <kittykatt@kittykatt.us>.

.SH REPORTING BUGS
Report bugs to <https://github.com/KittyKatt/bmpc/issues>

.SH COPYRIGHT
This is free software; you can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option) any later version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
